site_name: Cuadratura Gaussiana - Tarea 2
theme:
  name: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Introducción: index.md
  - Teoría y Explicación: explanation.md
  - Tutorial de Uso: tutorials.md
  - Referencia del Código: reference.md
